In [64]:
import pandas as pd

In [65]:
# Cargar ambos archivos
dataset = pd.read_csv('training_set_features.csv')
dataset_resultados = pd.read_csv('training_set_labels.csv')

In [66]:
# Imprimir una parte de ellos
dataset.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [67]:
# Imprimir una parte de los resultados
dataset_resultados.head()

   respondent_id  h1n1_vaccine  seasonal_vaccine
0              0             0                 0
1              1             0                 1
2              2             0                 0
3              3             0                 1
4              4             0                 0

In [68]:
# Seleccionar sÃ³lo una parte de las columnas
columnas = [
    "h1n1_concern", # Â¿QuÃ© tanto le preocupa el H1N1 del 0-3?
    "h1n1_knowledge", # Â¿QuÃ© tanto sabe del virus del 0-2?
    "behavioral_antiviral_meds", # Â¿Cree en antivacunas? 0 o 1
    "behavioral_avoidance", # Â¿Evita estar en pÃºblico? 0 o 1 
    "behavioral_wash_hands", # Â¿Lava regularmente sus manos? 0 o 1 
    "behavioral_large_gatherings", # Â¿EstÃ¡ en lugares con mucha gente con frecuencia? 0 o 1
    "behavioral_touch_face", # Â¿Toca su cara frecuentemente? 0 o 1 
    "doctor_recc_h1n1", # Â¿Su doctor recomendÃ³ vacunarse? 0 o 1 
    "opinion_h1n1_vacc_effective", # Â¿QuÃ© tan efectiva cree que es la vacuna del 1-5?
    "opinion_h1n1_risk", # Â¿QuÃ© tanto riesgo cree que tiene la vacuna del 1-5?
    "age_group", # Grupo de edad
    "education", # MÃ¡ximo grado de estudio
    "sex", # Sexo de la persona
    "income_poverty", # La cantidad de ingresos de la persona
    "employment_status", # Si la persona se encuentra empleada
]

dataset_columnas_interes = dataset[columnas]

In [69]:
# Seleccionar sÃ³lo las columnas de interÃ©s de la vacunaciÃ³n
columnas_resultados = [
    "h1n1_vaccine"
]
dataset_resultados_columnas = dataset_resultados[columnas_resultados]

In [70]:
# Obtener el dataset final
df = pd.concat([dataset_columnas_interes, dataset_resultados_columnas], axis=1)
# Borrar filas con datos faltantes
df = df.dropna()

In [80]:
# Obtener valores por cada columna
for c in df.columns:
    print(f'{c}: {sorted(df[c].unique().tolist())}')

h1n1_concern: [0, 1, 2, 3]
h1n1_knowledge: [0, 1, 2]
behavioral_antiviral_meds: [False, True]
behavioral_avoidance: [False, True]
behavioral_wash_hands: [False, True]
behavioral_large_gatherings: [False, True]
behavioral_touch_face: [False, True]
doctor_recc_h1n1: [False, True]
opinion_h1n1_vacc_effective: [1, 2, 3, 4, 5]
opinion_h1n1_risk: [1, 2, 3, 4, 5]
age_group: ['18 - 34 Years', '35 - 44 Years', '45 - 54 Years', '55 - 64 Years', '65+ Years']
education: ['12 Years', '< 12 Years', 'College Graduate', 'Some College']
sex: ['Female', 'Male']
income_poverty: ['<= $75,000, Above Poverty', '> $75,000', 'Below Poverty']
employment_status: ['Employed', 'Not in Labor Force', 'Unemployed']
h1n1_vaccine: [False, True]

In [89]:
# Remapear valores enteros
texto = ['age_group', 'education', 'sex', 'income_poverty', 'employment_status']

for c in df.columns:
    if c not in texto:
        df[c] = df[c].astype(int)

# Remapear booleanos
booleanos_extra = ['doctor_recc_h1n1', 'h1n1_vaccine']
mapeo_booleanos = { 0: 'f', 1: 't' }
for c in df.columns:
    if c.startswith('behavioral') or c in booleanos_extra:
        df[c] = df[c].map(mapeo_booleanos)

df.head()

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_wash_hands,behavioral_large_gatherings,behavioral_touch_face,doctor_recc_h1n1,opinion_h1n1_vacc_effective,opinion_h1n1_risk,age_group,education,sex,income_poverty,employment_status,h1n1_vaccine
0,1,0,f,f,f,f,t,f,3,1,55 - 64 Years,< 12 Years,Female,Below Poverty,Not in Labor Force,f
1,3,2,f,t,t,f,t,f,5,4,35 - 44 Years,12 Years,Male,Below Poverty,Employed,f
3,1,1,f,t,t,t,f,f,3,3,65+ Years,12 Years,Female,Below Poverty,Not in Labor Force,f
4,2,1,f,t,t,t,t,f,3,3,45 - 54 Years,Some College,Female,"<= $75,000, Above Poverty",Employed,f
5,3,1,f,t,t,f,t,f,5,2,65+ Years,12 Years,Male,"<= $75,000, Above Poverty",Employed,f

In [114]:
import itertools
cantidad_filas = 2800
# Crear archivo ARFF
with open('dataset.arff', 'w') as f:
    f.write('@RELATION h1n1')
    
    f.write('\n\n')
    
    # Imprimir lista de atributos
    quote = '"{}"'.format
    for c in df.columns:
        mapf = quote if c in texto else (lambda x: str(x))
        f.write(f"@ATTRIBUTE {c} {{{', '.join(map(mapf, sorted(df[c].unique().tolist())))}}}\n")
    
    f.write('\n')
    f.write('@DATA\n')
    rowf = lambda x: quote(x) if isinstance(x, str) and len(x) > 1 else x
    for r in itertools.islice(df.itertuples(), cantidad_filas):
        f.write(','.join(map(str, map(rowf, r[1:]))))
        f.write('\n')